// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfQad6cnFKuXZCrvF_CWuyHOMw1MLLYyg',
    appId: '1:490325365291:web:cd7db81d5a1ddbb143106e',
    messagingSenderId: '490325365291',
    projectId: 'tandag911',
    authDomain: 'tandag911.firebaseapp.com',
    storageBucket: 'tandag911.firebasestorage.app',
    measurementId: 'G-2TXPN12J5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIk9cV-k2wKmRBQG8x1YAs2lYHbtnp59E',
    appId: '1:490325365291:android:a378e2d2396866fd43106e',
    messagingSenderId: '490325365291',
    projectId: 'tandag911',
    storageBucket: 'tandag911.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8DyV4XHijiYFAC5O5sY8SvPSfhGUGDro',
    appId: '1:490325365291:ios:d98f6674d3e17cbd43106e',
    messagingSenderId: '490325365291',
    projectId: 'tandag911',
    storageBucket: 'tandag911.firebasestorage.app',
    iosBundleId: 'com.example.tandag911',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8DyV4XHijiYFAC5O5sY8SvPSfhGUGDro',
    appId: '1:490325365291:ios:d98f6674d3e17cbd43106e',
    messagingSenderId: '490325365291',
    projectId: 'tandag911',
    storageBucket: 'tandag911.firebasestorage.app',
    iosBundleId: 'com.example.tandag911',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfQad6cnFKuXZCrvF_CWuyHOMw1MLLYyg',
    appId: '1:490325365291:web:0edefed37e7153b143106e',
    messagingSenderId: '490325365291',
    projectId: 'tandag911',
    authDomain: 'tandag911.firebaseapp.com',
    storageBucket: 'tandag911.firebasestorage.app',
    measurementId: 'G-NK2Q1KF73L',
  );
}
